

You have worked with MyExposome on a demonstration project to identify the chemical compounds 
which were detected using wristbands which were worn for a period of time by members of your study group. We are using these wristband to report any detectable level of each of  **`r howManyChemicalsTested`** compounds.  

You were one of  **`r howManyWristbandsTested`** participants in this demonstration project. Your unique ID is:    **`r pureSubjectName`**.


**`r testExplanation`** 


The average number of chemicals found across all tested wristbands in this project was **`r round(averageNumberChemsFound,1) `**. 
The maximum number of chemicals found on any one wristband was **`r maxChemFoundOnAnyOneWristband`**.  The minimum number of chemicals found on any one wristband was **`r minChemFoundOnAnyOneWristband`**.    The total number of distinct chemicals found across all the wristbands in this study was **`r howManyUniqueChemFoundAcrossAllWristbands`**.    The standard deviation of the number of found chemicals per wristband was **`r stdDevChemFoundOnAnyOneWristband `**.  

&nbsp;



```{r  FAKE_empty, results='asis', echo=FALSE, message=FALSE}

testValueGroup<-TRUE


```







