---
title: "Cars Dataset with Tooltips"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(htmltools)
library(tidyr)
library(kableExtra)
library(pander)


```


```{r setup2, include=TRUE}
# Load the cars dataset
data(cars)

# Function to add tooltips to the speed column
add_tooltip2 <- function(value) {
  #paste0('<span title="Chemicals found in household goods, consumable items, and personal care products, including food, beverages, cosmetics, and cleaning supplies. These may serve as preservatives, fragrances, or active ingredients. ', "FKE VALUEe", '">',"value", '</span>')
  paste0('<span title="Tooltip for speed: ', value, '">', value, '</span>')
  #paste0('<span style="     " data-toggle="tooltip" data-container="body" data-placement="right" title="Tip 1">`r value`</span>')
  
}
#<span style="     " data-toggle="tooltip" data-container="body" data-placement="right" title="Tip 1">MISTAKE</span>


# Apply the function to the speed column
cars$speed <- sapply(cars$speed, add_tooltip2)



# Print the table with tooltips using kable  f11
kable(cars, format = "html", escape = FALSE) %>%
  kable_styling(full_width = F)



```


