

You have worked with MyExposome on a demonstration project to identify the chemical compounds 
which were detected using wristbands which were worn for a period of time by members of your study group. We are using these wristband to report any detectable level of each of  **`r howManyChemicalsTested`** compounds.  

There were  **`r howManyWristbandsTested`** wristbands in this demonstration project.   All analysis was done "blind" to any aspect of the underlying study design with unique  identifiers assigned to each wristband.

**`r testExplanation`** 

The average number of chemicals found across all tested wristbands in this project was **`r round(averageNumberChemsFound,1) `**. 
The maximum number of chemicals found on any one wristband was **`r maxChemFoundOnAnyOneWristband`**.  The minimum number of chemicals found on any one wristband was **`r minChemFoundOnAnyOneWristband`**.    The total number of distinct chemicals found across all the wristbands in this study was **`r howManyUniqueChemFoundAcrossAllWristbands`**.
<!-- The standard deviation of the number of found chemicals per wristband was **`r stdDevChemFoundOnAnyOneWristband `**.  -->

&nbsp;



```{r  FAKE_empty, results='asis', echo=FALSE, message=FALSE}

testValueGroup<-TRUE


```


******






