<!-- PRINT Headline Rule for total chemical GROUP as denoted by Silent Spring using a separate RMD file-->

<!--  Headlines for amount detected (by chemical group)     
We propose applying these headlines to each chemical group separately. The participant would receive the top priority headline that applies for each chemical group. The headlines are not exhaustive (i.e., not all participants will necessarily receive a headline for every group). The headlines are intended to highlight particularly high or low.  

SubClassScores seemss to already have manny values.  It shows how any of each category each person has.  SO for each CLASS (i.e. "Chemicals in Commerce") 
BUT subclassscores doesn't have enough detail to do this

You had some {group name} detected in your wristband that were not found in most others.

NEED to add "classification" if it isn't already to the big result table.  THEN we can do anything w/ a query on that table.

THIS IS COMPLICATED and unclear what I really want to display... TBD.

-->


```{r RunRcodeToFindClassificationMessages, results='asis', echo=FALSE, message=FALSE,fig.width=10, fig.height=4}

### Load the R code to fill in the value of report_messages

source(here("R","HeadlinesAmountByChemicalGroup_R_Code.R"), local = knitr::knit_global())

## Call the function
report_messages <- generate_report(subject, testResults.bigWithClass)


```


<!-- ## Key Messages By Chemical Classification -->

```{r printMessageForTotalChemByGroup, results='asis', echo=FALSE, message=FALSE,fig.width=10, fig.height=4}

### Load the R code to fill in the value of report_messages
#source("HeadlinesAmountByChemicalGroup_R_Code.R", local = knitr::knit_global())

if (!is.null(report_messages)) {
  cat("## Key Messages By Chemical Group\n")
    cat(paste0("Chemicals are often grouped based on how we’re exposed to them—through breathing, skin contact, or what we eat—and how we can avoid them, ",
    "like washing hands, improving ventilation, or restricting certain products. Here are some key points from your results. ",
    "Keep in mind that a chemical might show up in more than one group since chemicals can come from different sources.\n\n"  ) )
  # Print the messages
  for (message in report_messages) {
    cat("* ", message, "\n")
  }
}

#generate_report("AAG0AAG", testResults.bigWithClass)
#generate_report("AAG0AC0", testResults.bigWithClass)
#generate_report("AAGA00C", testResults.bigWithClass)
#generate_report("AAGA009", testResults.bigWithClass)
#generate_report("AAG0CAA", testResults.bigWithClass)
#generate_report("AAG0CAE", testResults.bigWithClass)


#cat("\n\n **This is not yet tested FULLY.  This is to print HEADLINE RULES by CHEM GROUP if we decide to do that** \n")


# 
```
