---
title: "TestPopups and Popovers and buttons"
output: 
  rmdformats::readthedown:
    self_contained: true
    number_sections: true
    toc_depth: 3
    df_print: "paged"
date: "2024-10-21"
---


```{r loadPackages, echo=FALSE}
library("htmltools")
#install.packages("bsplus")
library("bsplus")

```


```{r setupbs_modal_std_dev, echo=FALSE}


bs_modal(id = "StandardDevation", title = "Standard Deviation Definition", body = "Standard deviation is a measure of how spread out the numbers in a set are from the average. A bigger standard deviation means the numbers are more spread out, while a smaller one means they're closer to the average.")

# REMEMBER here is how to use a button
# bs_button("Standard Devation", button_type = "primary", class = "btn-xs btn-outline-info") %>%
#  bs_attach_modal(id_modal = "StandardDevation")
  
```



One important way to look at the data is, for each chemical, what was the smallest, largest, average, and middle value found, how many wristbands was it found on, and the `r bs_button("standard deviation", button_type = "primary", class = "btn-xs btn-outline-info") %>% bs_attach_modal(id_modal = "StandardDevation")`.


